# Generated by Django 2.2.1 on 2019-05-13 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20190513_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=1, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
