# Generated by Django 2.2.1 on 2019-05-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
